### ISSUE TITLE
网站标题log问题

### ISSUE THREAD

**Issue by 011011100** [trends-dev/trends.dev#11]
![image](https://user-images.githubusercontent.com/74953343/233823338-7aad2c42-44d9-4728-a5a2-0263d48506ba.png)
现在还是默认的log

**Comment by elonehoo** [comment]
@011011100 那我想我们确实需要一个适合我们的logo

**Comment by 011011100** [comment]
![image](https://user-images.githubusercontent.com/74953343/233825722-066f3dce-d3dd-4836-a275-49e99f712460.png)
原来你们不打算直接使用这个啊

**Comment by elonehoo** [comment]
但是他毕竟是svg格式的

**Comment by elonehoo** [comment]
也或者我们需要一个更适合我们logo

**Comment by 011011100** [comment]
确实有点草率，那你自己画一个吧 haha

**Comment by elonehoo** [comment]
:)

**Comment by elonehoo** [comment]
在 #13 我们修改了页面logo的显示
