### ISSUE TITLE
赞助商头像

### ISSUE THREAD

**Issue by 011011100** [trends-dev/trends.dev#12]
![image](https://user-images.githubusercontent.com/74953343/233827225-c8ca72fc-cd1e-43d2-9f99-676ebc1148d4.png)
夜间模式下赞助商的头像很丑，我不希望他们是反色的。可以改成灰色的或者别的吗

**Comment by wkx160312746** [comment]
我也是这么认为的

**Comment by 011011100** [comment]
给我改！好歹我交了钱

**Comment by elonehoo** [comment]
在 #13 我们在暗色模式讲头像恢复原来的颜色，使其观感更加舒适

**Comment by 011011100** [comment]
这就是当甲方的感觉吗好爽
谢谢你

**Comment by elonehoo** [comment]
但我想我们需要鞭策一下 @wkx160312746 ,我们栏目的负责人对于项目并不是特别上心

**Comment by 011011100** [comment]
i think so 。
Some people spend too much time on their girlfriends
