### ISSUE TITLE
赞助页面问题

### ISSUE THREAD

**Issue by 011011100** [trends-dev/trends.dev#14]
我很高兴能成为你们的赞助商
![image](https://user-images.githubusercontent.com/74953343/233891339-aa478c61-ca62-4bd8-b3d5-864e6cc81407.png)
同时我发现在夜间模式下，赞助页面的人物log的卡片背景出现了不统一的问题。
同时赞助页面是否应该附上赞助商的排名规则。

其次我对侧边栏下面的那一条黑黑的玩意很好奇，你们是否打算在在边上展示所有的赞助商？这个功能好像尚未实现。

**Comment by 011011100** [comment]
@wkx160312746

**Comment by elonehoo** [comment]
`下面的那一条黑黑的玩意` 是广告栏

**Comment by 011011100** [comment]
我能放一些虚拟的东西吗
假的广告什么的

**Comment by elonehoo** [comment]
如果你愿意支付广告费用，我想我们没有什么理由拒绝

**Comment by 011011100** [comment]
什么三流网站还要钱真是可恶1元一个月

**Comment by elonehoo** [comment]
:)
