### ISSUE TITLE
需要一个制度来让更多的人参与投稿

### ISSUE THREAD

**Issue by 011011100** [trends-dev/trends.dev#23]
如果我想要在这个项目中加入我自己的栏目或者文章，我需要怎么做

**Comment by elonehoo** [comment]
只需要 @trends-dev/boss 这里的人同意即可

**Comment by elonehoo** [comment]
@wkx160312746

**Comment by 011011100** [comment]
boos？
boss？

**Comment by elonehoo** [comment]
yep, Boss

**Comment by elonehoo** [comment]
不过好像他现在很难处理这些东西

**Comment by elonehoo** [comment]
当然，我想如果你可以给你的专题设计一个不错的名字，然后在提出PR，如果检查过没什么问题，我想他没有理由拒绝

**Comment by 011011100** [comment]
如果采用审核制度的话我希望能给出一份标准，或者是别的什么

**Comment by elonehoo** [comment]
@011011100 我们更想知道你想发布什么类型的内容

**Comment by elonehoo** [comment]
或者我们需要 @wkx160312746 的涉入

**Comment by 011011100** [comment]
我暂时还没有想好，只是突然想到了这一点。
同时我认为我们或许应该出版一个投稿的制度，让多数人参与到我们的这个项目中来。
不然我总感觉这就是我们自己人的自娱自乐罢了。
毕竟编程的潮流不能是我们说了算的对吧。

**Comment by elonehoo** [comment]
我想这个**提议**我们一定需要 @wkx160312746 的参与了

**Comment by 011011100** [comment]
他身为这个项目的boss，我认同你的观点 @trends-dev/boss

**Comment by wkx160312746** [comment]
当然可以, 不过现在主要是由 @elonehoo @wkx160312746 进行投稿, 如果有想要投稿的比如 @011011100 可以提交pr 由我们审核后就可以展现在官网

**Comment by 011011100** [comment]
是的是的这点我已经了解完毕了。提出pr 然后 审核 合并。我们现在想要知道的不是我要怎么提交文章，而是提交文章的制度是否需要被明确下来

**Comment by elonehoo** [comment]
我想一个网站的所有文章应该不约而同的统一。你也可以看到我们现在大部分文章都是
```markdown
<h1>标题</h1>
<div>头像</div>
```
组成

<img width="1710" alt="image" src="https://github.com/trends-dev/trends.dev/assets/43719490/3dfad69c-8877-470b-8157-07a0be59aafd">

**Comment by 011011100** [comment]
fine

**Comment by elonehoo** [comment]
今天晚些的时候，会出具一些编写的文档说明，到时候会关闭这个issue

**Comment by elonehoo** [comment]
十分感谢 @011011100 提出的好建议
